import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { currentMerchant } from "@/lib/snailon-ingest/merchant";
import type { SnailonPlatform } from "@/lib/snailon-ingest/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const PLATFORMS = new Set<SnailonPlatform>([
  "shopify",
  "woocommerce",
  "youcan",
  "storeino",
  "shopyan",
  "custom",
]);

/**
 * POST /api/stores
 *
 * Body: { name, platform, primary_domain }
 *
 * Creates a `store_connections` row + auto-registers the primary domain
 * (and its www. variant) in `store_domains` so the pixel works on both.
 *
 * The pixel_token (snk_xxx) and webhook_secret are auto-generated by
 * column DEFAULT in the v2 migration — we never set them client-side.
 */
export async function POST(req: Request) {
  const supabase = createClient();
  const me = await currentMerchant(supabase);
  if (!me) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  let body: { name?: unknown; platform?: unknown; primary_domain?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "malformed" }, { status: 400 });
  }

  const name = String(body.name ?? "").trim().slice(0, 200);
  const platform = String(body.platform ?? "").trim() as SnailonPlatform;
  const primaryDomain = sanitizeHostname(String(body.primary_domain ?? ""));

  if (!name) {
    return NextResponse.json({ error: "name_required" }, { status: 400 });
  }
  if (!PLATFORMS.has(platform)) {
    return NextResponse.json({ error: "invalid_platform" }, { status: 400 });
  }
  if (!primaryDomain) {
    return NextResponse.json({ error: "invalid_domain" }, { status: 400 });
  }

  const admin = createAdminClient();

  const { data: store, error: insErr } = await admin
    .from("store_connections")
    .insert({
      merchant_id: me.merchant_id,
      platform,
      store_name: name,
      store_url: `https://${primaryDomain}`,
      primary_domain: primaryDomain,
    })
    .select(
      "id, pixel_token, primary_domain, platform, store_name, connection_status"
    )
    .single();

  if (insErr || !store) {
    return NextResponse.json(
      { error: "create_failed", detail: insErr?.message },
      { status: 500 }
    );
  }

  // Auto-register apex + www so both work without merchant action.
  const hostnames = [primaryDomain];
  if (!primaryDomain.startsWith("www.")) {
    hostnames.push("www." + primaryDomain);
  }
  await admin.from("store_domains").insert(
    hostnames.map((hostname) => ({
      store_connection_id: store.id,
      hostname,
      verified_at: new Date().toISOString(),
    }))
  );

  return NextResponse.json({
    id: store.id,
    public_key: store.pixel_token,
    primary_domain: store.primary_domain,
    platform: store.platform,
    name: store.store_name,
    connection_status: store.connection_status,
    // webhook_secret NEVER returned — it's only used inside server-rendered
    // plugin downloads via /api/stores/[id]?include=plugin
  });
}

/**
 * GET /api/stores — list current merchant's stores.
 */
export async function GET() {
  const supabase = createClient();
  const me = await currentMerchant(supabase);
  if (!me) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const { data, error } = await supabase
    .from("store_connections")
    .select(
      "id, store_name, platform, primary_domain, pixel_token, connection_status, first_order_at, last_order_at, created_at"
    )
    .order("created_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: "fetch_failed" }, { status: 500 });
  }

  // Reshape to public-API contract — `name` and `public_key` rather than
  // the internal `store_name` / `pixel_token` column names.
  const stores = (data || []).map((s) => ({
    id: s.id,
    name: s.store_name,
    platform: s.platform,
    primary_domain: s.primary_domain,
    public_key: s.pixel_token,
    connection_status: s.connection_status,
    first_order_at: s.first_order_at,
    last_order_at: s.last_order_at,
    created_at: s.created_at,
  }));

  return NextResponse.json({ stores });
}

// =============================================================================
// helpers
// =============================================================================

function sanitizeHostname(input: string): string {
  if (!input) return "";
  let s = input.trim().toLowerCase();
  s = s.replace(/^https?:\/\//, "");
  s = s.split("/")[0].split("?")[0].split("#")[0];
  s = s.split(":")[0];
  if (!/^[a-z0-9](?:[a-z0-9.-]{0,253}[a-z0-9])?$/.test(s)) return "";
  if (!s.includes(".")) return "";
  return s;
}
